
items=bow
texture=chicken_bow
texture.bow_pulling_0=chicken_bow_pulling_0
texture.bow_pulling_1=chicken_bow_pulling_1
texture.bow_pulling_2=chicken_bow_pulling_2
nbt.display.Name=ipattern:*chicken bow*